alphabet = {'I': {'ATT', 'ATC', 'ATA'},
            'L': {'CTT', 'CTC', 'CTA', 'CTG', 'TTA', 'TTG'},
            'V': {'GTT', 'GTC', 'GTA', 'GTG'},
            'F': {'TTT', 'TTC'},
            'M': {'ATG'},
            'C': {'TGT', 'TGC'},
            'A': {'GCT', 'GCC', 'GCA', 'GCG'},
            'G': {'GGT', 'GGC', 'GGA', 'GGG'},
            'P': {'CCT', 'CCC', 'CCA', 'CCG'},
            'T': {'ACT', 'ACC', 'ACA', 'ACG'},
            'T': {'ACT', 'ACC', 'ACA', 'ACG'},
            'S': {'TCT', 'TCC', 'TCA', 'TCG', 'AGT', 'AGC'},
            'Y': {'TAT', 'TAC'},
            'W': {'TGG'},
            'Q': {'CAA', 'CAG'},
            'N': {'AAT', 'AAC'},
            'H': {'CAT', 'CAC'},
            'E': {'GAA', 'GAG'},
            'D': {'GAT', 'GAC'},
            'K': {'AAA', 'AAG'},
            'R': {'CGT', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG'},
            'X': {'TAA', 'TAG', 'TGA'},
            '+': {'ATG'}
            }


reverse_alphabet = {'GGC': 'G',
                    'GAG': 'E',
                    'GAA': 'E',
                    'TGT': 'C',
                    'AAT': 'N',
                    'TCT': 'S',
                    'GTC': 'V',
                    'TAG': 'X',
                    'CGA': 'R',
                    'GGG': 'G',
                    'CAG': 'Q',
                    'GAT': 'D',
                    'AAA': 'K',
                    'TGC': 'C',
                    'TTG': 'L',
                    'AAC': 'N',
                    'AGT': 'S',
                    'CCC': 'P',
                    'TCC': 'S',
                    'TAT': 'Y',
                    'CTG': 'L',
                    'AGA': 'R',
                    'CAA': 'Q',
                    'TCA': 'S',
                    'GCC': 'A',
                    'CTA': 'L',
                    'GTA': 'V',
                    'ACA': 'T',
                    'GAC': 'D',
                    'GCG': 'A',
                    'TAC': 'Y',
                    'CTT': 'L',
                    'AGC': 'S',
                    'CTC': 'L',
                    'TTA': 'L',
                    'CGG': 'R',
                    'TGA': 'X',
                    'TCG': 'S',
                    'ATA': 'I',
                    'TGG': 'W',
                    'AGG': 'R',
                    'GTT': 'V',
                    'CCT': 'P',
                    'ATG': 'M',
                    'GTG': 'V',
                    'TTT': 'F',
                    'ACC': 'T',
                    'CCA': 'P',
                    'ATC': 'I',
                    'GCA': 'A',
                    'CAT': 'H',
                    'ATT': 'I',
                    'CAC': 'H',
                    'GCT': 'A',
                    'AAG': 'K',
                    'TAA': 'X',
                    'CGC': 'R',
                    'ACG': 'T',
                    'ACT': 'T',
                    'GGA': 'G',
                    'GGT': 'G',
                    'TTC': 'F',
                    'CCG': 'P',
                    'CGT': 'R'}
